micronaut:
  server:
    port:8080
  application:
    name: clientScylla3
cassandra:
  default:
    basic:
      contact-points:
        - 127.0.0.1:9042
      session-keyspace: mydata
      load-balancing-policy:
        local-datacenter: datacenter1
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true

